### ISSUE TITLE
Using BARTpho for Text summarization on Vietnamese

### ISSUE THREAD

**Issue by thaokimctu** [VinAIResearch/BARTpho#10]
Thank you so much for this fantastic work. I'm currently doing research on BART model and having some questions regarding to BARTpho model in need for elaborating.
I have been using this training paradigm https://github.com/yixinL7/BRIO for text summarization, they used the pretrained BART model, facebook/bart-large-cnn as baseline and achieved pretty good result on CNN/DM dataset. I figured I could replaced the baseline model with BARTpho and do the same with my custom dataset. But the cross validation during training was quite poor no matter how I change the configuration. 
So my question are: 
- Do I need to finetune BARTpho model on my custom dataset, I guess the facebook/bart-large-cnn model is able to achieve good result because it already trained on CNN/DM dataset.
- If I do then can you show me how to finetune BARTpho on colab, since it a large model and I don't think colab has enough resources.

**Comment by datquocnguyen** [comment]
> Do I need to finetune BARTpho model on my custom dataset, I guess the facebook/bart-large-cnn model is able to achieve good result because it already trained on CNN/DM dataset.

Yes, you'd have to fine-tune BARTpho on your custom dataset first, and then use the fine-tuned model in the same manner as for `facebook/bart-large-cnn`

> If I do then can you show me how to finetune BARTpho on colab, since it a large model and I don't think colab has enough resources.

See example: https://github.com/VinAIResearch/BARTpho/issues/2#issuecomment-1146988402 You might want to try the "base" versions `vinai/bartpho-syllable-base`/`vinai/bartpho-word-base` w.r.t. a limited computational resource.

**Comment by thaokimctu** [comment]
Thank you so much. I'll try that, but in case I still have more questions, can I ask them under this issue?
