### ISSUE TITLE
Cannot load BartPhoTokenizer from pretrained when work with huggingface/transformers

### ISSUE THREAD

**Issue by hduc-le** [VinAIResearch/BARTpho#3]
Hi authors,

I get an error when I load the tokenizer from pretrained as bellow:
---
from transformers import AutoModel, AutoTokenizer
bartpho_syllable = AutoModel.from_pretrained("vinai/bartpho-syllable")
syllable_tokenizer = AutoTokenizer.from_pretrained("vinai/bartpho-syllable", use_fast=True)
--
>> AttributeError: module transformers.models.bartpho has no attribute BartphoTokenizer

I'm using Google Colab. Could you guys let me know how to overcome this issue.
Thanks.
![image](https://user-images.githubusercontent.com/71626184/141227275-2678f27a-203d-418f-b0a2-f30ef2e9de6c.png)

**Comment by datquocnguyen** [comment]
Have you tried install `transformers` v4.12+ or install `transformers` from its latest source?
    
    git clone https://github.com/huggingface/transformers.git
    cd transformers
    pip3 install --upgrade .

And also clean/remove  your folder `~/.cache/huggingface/transformers`, so it'd automatically re-download BARTpho properly. It should work.

**Comment by hduc-le** [comment]
Thank you for replying. I've tried all steps in your above comment. I also checked the transformers version and cleaned/removed the folder ~/.cache/huggingface/transformers, But I still get the same error!!!
![image](https://user-images.githubusercontent.com/71626184/141251880-a21324c3-ae7f-4a84-a0bc-fa7bb92fc9f6.png)

**Comment by datquocnguyen** [comment]
@hduc-le `use_fast=False` BartphoTokenizer does not support a fast version atm.

**Comment by hduc-le** [comment]
Finally, I've figured out a solution for the issue. I've changed the way of loading the pre-trained tokenizer from importing 'AutoTokenizer' to 'BartphoTokenizer' directly. Here is my code:
-----
from transformers import AutoModel, BartphoTokenizer

model = AutoModel.from_pretrained("vinai/bartpho-syllable")
tokenizer = BartphoTokenizer.from_pretrained("vinai/bartpho-syllable")
-----
Note: make sure that you installed the 'sentencepiece' package before.
It works for me. But I don't know why does AutoTokenizer not figure out the 'BartphoTokenizer' on Google Colab.

**Comment by datquocnguyen** [comment]
it's weird.
Did this following example work?

```
#BARTpho-syllable
syllable_tokenizer = AutoTokenizer.from_pretrained("vinai/bartpho-syllable", use_fast=False)
bartpho_syllable = AutoModel.from_pretrained("vinai/bartpho-syllable")
TXT = 'Chúng tôi là những nghiên cứu viên.'  
input_ids = syllable_tokenizer(TXT, return_tensors='pt')['input_ids']
features = bartpho_syllable(input_ids)
```

**Comment by hduc-le** [comment]
@datquocnguyen It's actually weird. I really have no idea what happened to my code. But your code example works for me now. Sorry for taking up so much of your time, I appreciate it!!!
