### ISSUE TITLE
What is your decoder_start_token_id

### ISSUE THREAD

**Issue by demdecuong** [VinAIResearch/BARTpho#4]
Could you update the decoder_start_token_id in the model.config because I found None in the `config.json`

Thank you.

**Comment by demdecuong** [comment]
My bad, I mistakenly thought BART was the same as T5

**Comment by datquocnguyen** [comment]
Please specify the reason for this update.

**Comment by datquocnguyen** [comment]
`decoder_start_token_id` is set to 2. 
https://stackoverflow.com/questions/64904840/why-we-need-a-decoder-start-token-id-during-generation-in-huggingface-bart 

The conversion code from fairseq to huggingface did not produce this parameter. So I was not aware of this. 

Relevant issue: https://github.com/VinAIResearch/BARTpho/issues/2
