### ISSUE TITLE
Whrere is `config.json` file?

### ISSUE THREAD

**Issue by thaondc** [VinAIResearch/BARTpho#5]
Hi @datquocnguyen,

I am so attracted by your project. I followed your tutorial and try to train a new model, but I can not find `config.json` in `fairseq-bartpho-word.zip`. Can you tell me how to get it?

Thank you.

**Comment by datquocnguyen** [comment]
Hi, the fairseq version does not have the `config.json` file.

**Comment by thaondc** [comment]
Hi, And with tranformers, how can I get config.json?

**Comment by thaondc** [comment]
> Hi, with tranformers, how can I get config.json?

**Comment by datquocnguyen** [comment]
https://huggingface.co/vinai/bartpho-word/tree/main

**Comment by thaondc** [comment]
Thank you very much. Merry Christmas anh :)))
