### ISSUE TITLE
Cannot load BartPhoTokenizer when i load the tokenizer use syllabel

### ISSUE THREAD

**Issue by LuuDucCanh** [VinAIResearch/BARTpho#6]
When i try to load to load the tokenizer use syllable, i get an error "module transformers.models.bartpho has no attribute BartPhoTokenizer".
i used transformers 4.15.0. I tried to clean my folder ~/.cache/huggingface/transformers but i still get the same error.
Can you help me! Thanks.
![image](https://user-images.githubusercontent.com/62085576/147804925-023c09cf-9562-45e8-9057-931bb4f56224.png)

**Comment by datquocnguyen** [comment]
It's weird. The tokenizer is already available on transformers: https://github.com/huggingface/transformers/tree/3d587c53432c7c392aa08f582015c846ca076540/src/transformers/models/bartpho 
Can you try reinstall transformers version 4.12.0 and see whether the error still happens?

**Comment by datquocnguyen** [comment]
Please could you also help post this issue to huggingface's transformers ? Thanks.

**Comment by LuuDucCanh** [comment]
i've tried reinstall transformers version 4.12.0 but i still get this error

**Comment by datquocnguyen** [comment]
<img width="682" alt="Screen Shot 2021-12-31 at 3 22 01 pm" src="https://user-images.githubusercontent.com/2412555/147812045-ea01b643-e548-4368-b6de-58b999fcb287.png">
I just tried reinstalling transformers, and it works without any error w.r.t. the tokenizer.

**Comment by datquocnguyen** [comment]
It might be the case that your Python IDE was not configured with a proper Python version and transformers library?

**Comment by LuuDucCanh** [comment]
![image](https://user-images.githubusercontent.com/62085576/147813633-2eecb741-0d98-477a-9bee-853685d6f654.png)
i have this error when i reinstall transformers version 4.12.0. How can i fix this error

**Comment by datquocnguyen** [comment]
It's "vinai/bartpho-syllable", not "vinai/bartpho-syllablel".

**Comment by LuuDucCanh** [comment]
![image](https://user-images.githubusercontent.com/62085576/147820219-7d60631a-fe86-42b5-b158-309bd7b07df6.png)
i am sorry about that, but i still get the same error

**Comment by datquocnguyen** [comment]
https://huggingface.co/docs/transformers/model_doc/bartpho is available since version 4.12.0.
I cannot help. I have no idea what's going on with your installation/configuration.

**Comment by LuuDucCanh** [comment]
I appreciate your help so much.

**Comment by datquocnguyen** [comment]
Did you install sentencepiece: `pip install sentencepiece`

**Comment by datquocnguyen** [comment]
From Nguyen Luong Tran: 
https://github.com/huggingface/transformers/issues/9862#issuecomment-787481015 
=> reset runtime and install sentencepiece.

**Comment by LuuDucCanh** [comment]
i tried to reset colab runtime and install sentencepiece, it's work for me. Thank you so much.
